#Enable tmux to support UTF-8 characters (Nerd Fonts)


# Enable Colours
set -g default-terminal 'tmux-256color'
set -as terminal-overrides ',*:Tc'

# Prefix Key
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Create new session
bind N new-session

# Open new windows in current directory path
bind c new-window -c "#{pane_current_path}"

# Split Windows
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Reload Config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "󰑓 Config reloaded"

# Resize Panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

# Enable Mouse
set -g mouse on

# Scrollback
set -g history-limit 50000

# VIM motions
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Enable Mouse Dragging
unbind -T copy-mode-vi MouseDragEnd1Pane

# Status Line Position
set-option -g status-position top

# Make zsh default
set-option -g default-shell /bin/zsh

# Tell TPM  where the plugins actually live
set -g @tpm_plugins_path '~/.config/tmux/plugins/'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# Tmux save with name
bind S display-popup -E ~/.config/tmux/scripts/tmux-save-as.sh

##### Theme: Duskfox #####
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/duskfox/duskfox.tmux
set -g status-style bg='#191726',fg='#cdcbe0'
set -g message-style bg='#232136',fg='#cdcbe0'
set -g pane-border-style fg='#393552'
set -g pane-active-border-style fg='#569fba'
set -g mode-style bg='#cdcbe0',fg='#191726'

set -g status-left-length 60
set -g status-left "#[fg=#569fba,bg=#191726]#[fg=#191726,bg=#569fba,bold] #S  #[fg=#569fba,bg=#191726]"

set -g status-right-length 120
set -g status-right "#[fg=#191726]#[fg=#cdcbe0,bg=#191726] 󰥔 %H:%M #[fg=#cdcbe0] #[fg=#908caa]󰃭 %Y-%m-%d #[fg=#191726]#[fg=#ea9a97,bg=#191726] 󰅒 #(whoami)@#H "

set -g window-status-format "#[fg=#6e6a86] 󰈚 #I:#W "
set -g window-status-current-format "#[fg=#cdcbe0,bg=#393552,bold] 󰈚 #I:#W #[default]"
set -g window-status-separator ""

##### Auto Save / Restore #####
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'session'
set -g @resurrect-hook-post-save-all 'bash ~/scripts/tmux-resurrect-cleanup.sh'
# set -g @continuum-save-interval '5'


##### Pop-Up: Session List #####
# prefix + w opens a custom tmux menu
bind w display-popup -E -w 30% -h 50% ~/.config/tmux/scripts/tmux-menu.sh

##### Pop-Up: Scratch Pad #####
# unbind -T popup Tab # prefix + t opens the scratchpad

unbind T
bind C-t display-popup -E -w 80% -h 80% ~/.config/tmux/scripts/tmux-scratch.sh
# bind -T popup t send-keys t  # send 't' as a regular keystroke (prevent close)
# bind -T popup q send-keys q  # send 'q' as a regular keystroke (prevent close)
bind -n -T popup C-t detach
bind -T popup C-[ copy-mode

# Pick checkpoint to restore
bind-key C-c display-popup -E -w 60% -h 60% ~/.config/tmux/scripts/tmux-checkpoint.sh


# Make Ctrl-l behave like terminal clear
bind  C-l send-keys C-l

run '/home/victor/.tmux/plugins/tpm/tpm'
